import axios from 'axios';
const apiClient = axios.create({ baseURL: import.meta.env.VITE_API_URL || 'http://localhost:5000/api' });
export const getBio = () => apiClient.get('/bio').then((r) => r.data);
export const getArtworks = (params = {}) => apiClient.get('/artworks', { params }).then((r) => r.data);
export const getArtworkById = (id) => apiClient.get(`/artworks/${id}`).then((r) => r.data);
export const createArtwork = (data, token) => apiClient.post('/admin/artworks', data, { headers: { Authorization: `Bearer ${token}` } }).then((r) => r.data);
export const updateArtwork = (id, data, token) => apiClient.put(`/admin/artworks/${id}`, data, { headers: { Authorization: `Bearer ${token}` } }).then((r) => r.data);
export const deleteArtwork = (id, token) => apiClient.delete(`/admin/artworks/${id}`, { headers: { Authorization: `Bearer ${token}` } }).then((r) => r.data);
export const submitContactForm = (data) => apiClient.post('/contact', data).then((r) => r.data);
export const createPaymentOrder = (data) => apiClient.post('/orders/create-payment-order', data).then((r) => r.data);
export const verifyPayment = (data) => apiClient.post('/orders/verify-payment', data).then((r) => r.data);
export const getOrderById = (orderId) => apiClient.get(`/orders/track/${encodeURIComponent(orderId)}`).then((r) => r.data);
export const adminLogin = (data) => apiClient.post('/admin/login', data).then((r) => r.data);
export const getContacts = (token) => apiClient.get('/admin/contacts', { headers: { Authorization: `Bearer ${token}` } }).then((r) => r.data);
export const getAdminOrders = (token) => apiClient.get('/admin/orders', { headers: { Authorization: `Bearer ${token}` } }).then((r) => r.data);
export const updateOrderStatus = (id, status, token) => apiClient.patch(`/admin/orders/${id}/status`, { status }, { headers: { Authorization: `Bearer ${token}` } }).then((r) => r.data);
export default apiClient;
